### ISSUE TITLE
why does PyCharm complain about this?

### ISSUE THREAD

**Issue by eubinean** [eubinecto/algodata#2]
https://github.com/eubinecto/algodata/blob/1209783f53ce50b626536c3fb124fe28fa3424c8/ch8/eubin/trees.py#L88

<img width="608" alt="image" src="https://user-images.githubusercontent.com/56193069/85913842-25042580-b873-11ea-8696-b3694afdab86.png">

이미 `ArrayBinaryTree`와 `LinkedBinaryTree`에서 모든 메소드를 implement하는데 왜 저기서 구현을 해야한다고 워닝을 하는지?

**Comment by ArtemisDicoTiar** [comment]
Abstract Base Class 임을 표시해야하는 것 같음.
BinaryTree는 ArrayBinaryTree와 LinkedBinaryTree의 Base Class이며 Abstract한 형태를 가지므로 ABCmeta를 표현해야 할 것 같음.
[https://dojang.io/mod/page/view.php?id=2389](https://dojang.io/mod/page/view.php?id=2389)

**Comment by eubinean** [comment]
@ArtemisDicoTiar 
똑같은 방법은 아닌데, 이렇게 해결함. 근데 어떻게 해결했는지 모르겠음 ㅋㅋㅋㅋㅋhttps://github.com/eubinecto/algodata/commit/7f75046d80d416475071b5953a5c8de0436cdd4c

**Comment by ArtemisDicoTiar** [comment]
응응 이게 그 ABC 표시하는 거 인듯 Abstract Base Class 근데 이게 왜 해결책인지는 정확히 모르겠어 ㅋㅋㅋ
약간 그 추상 베이스라는 상위 클래스를 만들어서 제공하나?
